<?php

namespace core\modules\manage;
use core\modules\tasks\repositories\TaskRepositoryInterface;
use PHPUnit\Framework\MockObject\RuntimeException;


/**
 * TaskModule module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'core\modules\manage\controllers';

    public $defaultRoute='manage/index';

    private $tasks;
    private $taskModule;

    public function init()
    {
        if (!$this){
            throw new RuntimeException();
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function setTaskModule($taskModule){
        $this->taskModule=$taskModule;
        if (is_subclass_of($taskModule::getTasks(),TaskRepositoryInterface::class)){
            $this->tasks=$taskModule::getTasks();
        }else{
            throw new \RuntimeException();
        }
    }

    public function getTasks(){
        return $this->tasks;
    }

}
